// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview AI-powered medication search flow for doctors.
 *
 * - medicationSearch - A function that searches for medications, their alternatives, and related information.
 * - MedicationSearchInput - The input type for the medicationSearch function.
 * - MedicationSearchOutput - The return type for the medicationSearch function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const MedicationSearchInputSchema = z.object({
  medicationName: z.string().describe('The name of the medication to search for.'),
});
export type MedicationSearchInput = z.infer<typeof MedicationSearchInputSchema>;

const MedicationSearchOutputSchema = z.object({
  searchResults: z.string().describe('Detailed information about the medication, alternatives, and related medical information.'),
});
export type MedicationSearchOutput = z.infer<typeof MedicationSearchOutputSchema>;

export async function medicationSearch(input: MedicationSearchInput): Promise<MedicationSearchOutput> {
  return medicationSearchFlow(input);
}

const medicationSearchPrompt = ai.definePrompt({
  name: 'medicationSearchPrompt',
  input: {schema: MedicationSearchInputSchema},
  output: {schema: MedicationSearchOutputSchema},
  prompt: `You are an AI assistant for doctors. Your task is to provide comprehensive information about medications, including alternatives and related medical information.

  Based on the medication name provided, research and summarize the following:

  - Uses and indications
  - Dosage and administration
  - Contraindications and precautions
  - Adverse effects
  - Drug interactions
  - Alternatives (if any)
  - Related medical information and studies

  Medication Name: {{{medicationName}}}
  `,
});

const medicationSearchFlow = ai.defineFlow(
  {
    name: 'medicationSearchFlow',
    inputSchema: MedicationSearchInputSchema,
    outputSchema: MedicationSearchOutputSchema,
  },
  async input => {
    const {output} = await medicationSearchPrompt(input);
    return output!;
  }
);
