// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview An AI tool that suggests possible diagnoses based on the patient's symptoms, vitals, and medical history.
 *
 * - suggestDiagnosis - A function that suggests diagnoses based on patient information.
 * - SuggestDiagnosisInput - The input type for the suggestDiagnosis function.
 * - SuggestDiagnosisOutput - The return type for the suggestDiagnosis function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestDiagnosisInputSchema = z.object({
  symptoms: z.string().describe('The symptoms reported by the patient.'),
  vitals: z.string().describe('The patient vitals, such as temperature and blood pressure.'),
  medicalHistory: z.string().optional().describe('The patient medical history.'),
});
export type SuggestDiagnosisInput = z.infer<typeof SuggestDiagnosisInputSchema>;

const SuggestDiagnosisOutputSchema = z.object({
  suggestedDiagnoses: z.string().describe('The AI-suggested possible diagnoses based on the provided information.'),
});
export type SuggestDiagnosisOutput = z.infer<typeof SuggestDiagnosisOutputSchema>;

export async function suggestDiagnosis(input: SuggestDiagnosisInput): Promise<SuggestDiagnosisOutput> {
  return suggestDiagnosisFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestDiagnosisPrompt',
  input: {schema: SuggestDiagnosisInputSchema},
  output: {schema: SuggestDiagnosisOutputSchema},
  prompt: `You are an AI assistant helping doctors by suggesting possible diagnoses based on the patient's symptoms, vitals, and medical history.

  Symptoms: {{{symptoms}}}
  Vitals: {{{vitals}}}
  Medical History: {{{medicalHistory}}}

  Based on the information above, suggest possible diagnoses. Be as specific as possible.
  `,
});

const suggestDiagnosisFlow = ai.defineFlow(
  {
    name: 'suggestDiagnosisFlow',
    inputSchema: SuggestDiagnosisInputSchema,
    outputSchema: SuggestDiagnosisOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
