// This is an autogenerated file from Firebase Studio.

import { z } from 'zod';

export const UserSchema = z.object({
  name: z.string(),
  email: z.string().email(),
  password: z.string(),
  role: z.enum(['Admin', 'Doctor', 'Receptionist']),
});

export type User = z.infer<typeof UserSchema>;
